USE [master]
GO

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'@DATABASE_NAME@')
BEGIN
	/* Database exist so we will kill all connections first... minimize chance of build failure due to a open query window */
	--     
	ALTER DATABASE [@DATABASE_NAME@] SET SINGLE_USER WITH ROLLBACK IMMEDIATE	
	ALTER DATABASE [@DATABASE_NAME@] SET MULTI_USER	
END
GO

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'@DATABASE_NAME@')
	DROP DATABASE [@DATABASE_NAME@]
GO

CREATE DATABASE [@DATABASE_NAME@]  
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO

ALTER DATABASE [@DATABASE_NAME@] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET ARITHABORT OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [@DATABASE_NAME@] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [@DATABASE_NAME@] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET  DISABLE_BROKER 
GO

ALTER DATABASE [@DATABASE_NAME@] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [@DATABASE_NAME@] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET RECOVERY FULL 
GO

ALTER DATABASE [@DATABASE_NAME@] SET  MULTI_USER 
GO

ALTER DATABASE [@DATABASE_NAME@] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [@DATABASE_NAME@] SET DB_CHAINING OFF 
GO

ALTER DATABASE [@DATABASE_NAME@] SET READ_WRITE 
GO